### 3.2.1从Python列表到PyTorch张量 p42
##### 以下是对列表索引的引用

In [4]:
a = [1.0, 2.0, 1.0]

In [5]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

### 3.2.2 构造我们的第一个张量 p43

In [2]:
import torch # <1>torch包含了多维张量的数据结构以及基于其上的多种数学操作
a = torch.ones(3) # <2>创建大小为3且值为1的一维张量
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1]) #类型转换

1.0

In [7]:
a[2] = 2.0 #修改内容
a

tensor([1., 1., 2.])

### 3.2.3 张量的本质 p44
> 通过将Xs存储在偶数索引中并将Ys存储在奇数索引中来生成一维张量 坐标

In [2]:
points = torch.zeros(6) # <1>使用.zeros只是获取适当大小的数组的一种方法 返回一个全为标量0的张量
points[0] = 4.0 # <2>我们用我们实际想要的值覆盖这些零
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

> 我们还可以将Python列表传递给构造函数，以达到和上面赋值相同的效果

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])# torch.Tensor是默认的tensor类型（torch.FlaotTensor）的简称
points

tensor([4., 1., 5., 3., 2., 1.])

> 获取第一个点的坐标

In [3]:
float(points[0]), float(points[1])

(4.0, 1.0)

> 我们也可以使用2D张量

In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

> 查看张量大小

In [5]:
points.shape

torch.Size([3, 2])

> 可以使用零或一来初始化张量，然后提供张量大小就可以了

In [13]:
points = torch.zeros(3, 2) #三行两列
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

> 现在我们可以使用两个索引访问张量中的单个元素

In [15]:
points[0, 1]

tensor(1.)

> 访问张量中的第一个元素，以获取第一个点的二维坐标

In [16]:
points[0]

tensor([4., 1.])

### 3.7 张量存储 
#### 3.7.1 Indexing into storage p54

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage() #保存成一个连续的数组,实际存储的形式

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [15]:
points_storage = points.storage()
points_storage[0]

4.0

In [19]:
points.storage()[1]

1.0

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points,points.shape 

(tensor([[2., 1.],
         [5., 3.],
         [2., 1.]]), torch.Size([3, 2]))

### 3.8.1 Views of another tensor’s storage p56

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point,second_point.storage_offset() #second_point在存储中的偏移量为2

(tensor([5., 3.]), 2)

In [22]:
second_point.size() # 同shape

torch.Size([2])

In [23]:
second_point.shape

torch.Size([2])

In [24]:
points.stride() # points张量的步长

(2, 1)

In [25]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [26]:
second_point.storage_offset()

2

In [27]:
second_point.stride()

(1,)

> 次张量与原始点张量是相同的存储,这也意味着更改次张量将对原始张量产生作用

In [28]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

> 我们可以把次张量克隆到新的张量中

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 3.8.2 Transposing without copying
> .t()对其进行转置操作

In [31]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

> 两个张量共享相同的存储 步长不同 通过改变元数据实现操作

In [32]:
id(points.storage()) == id(points_t.storage())

True

In [33]:
points.stride()

(2, 1)

In [34]:
points_t.stride() 

(1, 2)

### 3.8.3 Transposing in higher dimensions 调换维数 p60

> 在Pyorch中进行转置不仅限于矩阵 我们可以通过指定应该发生转置的两个维度
> transpose(a,b):交换a b两个维度的维数 

In [5]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [36]:
transpose_t.shape

torch.Size([5, 4, 3])

In [37]:
some_t.stride() #需要跨20

(20, 5, 1)

In [38]:
transpose_t.stride()

(1, 5, 20)

### 3.8.4 Contiguous tensors p60 连续张量
> is_contiguous 判断是是否是连续的

In [39]:
points.is_contiguous()

True

In [40]:
points_t.is_contiguous()

False

In [41]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [43]:
points_t.stride()

(1, 2)

> 我们可以使用contiguous方法从不连续的张量中获得一个连续的张量

In [44]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [46]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

### 3.5.3 管理张量的dtype属性 p51
> 为了分配正确数值类型的张量，我们可以指定适当的dtype作为构造函数的参数

In [47]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [48]:
short_points.dtype

torch.int16

> 对于已经创建的Tensor，可以使用内置方法进行类型转换 当不同数据类型的Tensor进行计算时，Pytorch会自动向高类型看齐

In [10]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [11]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [51]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>rand将张量元素初始化为0到1之间的随机数。
points_short = points_64.to(torch.short)
points_64 * points_short  # Pythorch 1.3以后的版本

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [6]:
# 重制一下
import torch
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

### 3.3 张量索引 p46

In [2]:
some_list = list(range(6))# [0, 1, 2, 3, 4, 5]
some_list[:]     # <1>所有元素
some_list[1:4]   # <2>第1（含）到第4（不含）个元素
some_list[1:]    # <3>第1（含）个之后所有元素
some_list[:4]    # <4> 第4（不含）个之前所有元素
some_list[:-1]   # <5>最末尾（不含）元素之前所有元素
some_list[1:4:2] # <6>范围1（含）到4（不含），步长为2的元素

[1, 3]

In [7]:
points[1:]       # <1>第1行及之后所有行，所有列
points[1:, :]    # <2>第1行及之后所有行，所有列
points[1:, 0]    # <3>第1行及之后所有行，仅第0列
points[None]     # <4>所有行，所有列
# points[:,:]

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 3.10 NumPy interoperability

In [55]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

> 从NumPy数组获得PyTorch张量

In [56]:
points = torch.from_numpy(points_np)

### 3.12 Serializing tensors p66
> 将points张量保存到ourpoints.t文件中

In [8]:
torch.save(points, '../p1ch3/ourpoints.t')

In [9]:
with open('../p1ch3/ourpoints.t','wb') as f: #保存
   torch.save(points, f)

In [10]:
points = torch.load('../p1ch3/ourpoints.t')

In [11]:
with open('../p1ch3/ourpoints.t','rb') as f: #加载
   points = torch.load(f)

#### 3.12.1 Serializing to HDF5 with h5py p67

In [12]:
import h5py

f = h5py.File('../p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())#coords是传入HDF5文件的键值
f.close()

In [13]:
f = h5py.File('../p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:] #请求数据集中的第二行和最后一行

In [14]:
last_points = torch.from_numpy(dset[-2:])# 数据将复制到张量存储中
f.close()
#last_points

###  3.9.1 Managing a tensor’s device attribute p63

In [22]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

> 将在CPU上创建的张量复制到GPU上

In [23]:
points_gpu = points.to(device='cuda')

> 如果我们的机器有多个GPU，我们也可以通过传递一个从零开始的整数 来确定分配给哪个GPU

In [24]:
points_gpu = points.to(device='cuda:0')

In [25]:
points = 2 * points  # <1>在CPU上执行乘法
points_gpu = 2 * points.to(device='cuda')  # <2>在GPU上执行乘法

> 计算出的结果，points_gpu张量不会被带回CPU

In [26]:
points_gpu = points_gpu + 4

In [27]:
points_cpu = points_gpu.to(device='cpu')

> 使用to的好处是可以通过提供device和dtype参数来同时更改位置和数据类型

In [28]:
points_gpu = points.cuda()  # <1>默认为GPU索引0
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

### 3.6 张量API  p52

In [71]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [72]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

#### 3.7.2 Modifying stored values: In-place operations 就地修改 p55

In [73]:
a = torch.ones(3, 2)

In [74]:
a.zero_() #_直接改变原张量
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])